### ISSUE TITLE
No sql beyond SET sql_mode='NO_AUTO_VALUE_ON_ZERO';

### ISSUE THREAD

**Issue by v3nt** [deliciousbrains/wp-migrate-db#56]
This is all i get. I've played around with the settings a lot and not joy!

# WordPress MySQL database migration
#
# Generated: Monday 16. November 2015 12:06 UTC
# Hostname: localhost
# Database: `reformarchdb`
# --------------------------------------------------------

/*!40101 SET NAMES utf8 */;

SET sql_mode='NO_AUTO_VALUE_ON_ZERO';

**Comment by olliekav** [comment]
This is all I get as well using WP Migrate Pro. Tried every variation of settings.

**Comment by leepowellcouk** [comment]
Same problem here

**Comment by dodge107** [comment]
Same here

**Comment by ChrisChiera** [comment]
Same issue here. Is this thread being monitored as looks like it was opened a year ago but no response from the developers?

**Comment by JRGould** [comment]
This issue is more than likely due to a php error, server error , or possibly database corruption. I'd recommend making sure that the `gzip` option is disabled in case gzip is misconfigured on your server and disabling your plugins and switching to the default theme to ensure that there are no errors being introduced by other third party code. 

I'm closing this thread, as don't usually provide support in this repository. If you have a bug to report, please do so here - otherwise you can post in the [community support forums](https://wordpress.org/support/plugin/wp-migrate-db)
