### ISSUE TITLE
Migrate faile (#113) at wp_post_meta

### ISSUE THREAD

**Issue by DonnaEIT** [deliciousbrains/wp-migrate-db#71]
Is there a table size limit for the migrate to work? In my DB this table that it fails on is 45mb. The table has no errors, and has been optimized. From what I can tell, I'm stuck with the size...I'm wondering if that's why it fails. I have plenty of memory (128mb) so that's not the reason...

**Comment by aaemnnosttv** [comment]
There is no limit on table size, only on chunk size as larger tables are done in pieces. Please see the [documentation here](https://deliciousbrains.com/wp-migrate-db-pro/doc/error-codes/#error-113) for that error and try the recommended steps there first.

If you're still having trouble and are not a WP Migrate DB Pro customer, we recommend reaching out to the community on the plugin's [wordpress.org support forum](https://wordpress.org/support/plugin/wp-migrate-db). Otherwise you may submit a support request using the form on the Help tab of the plugin.

**Comment by DonnaEIT** [comment]
What is the chunk size limitation please?

**Comment by aaemnnosttv** [comment]
It's controlled on the Settings tab as "Maximum Request Size".  It won't cause your migration to fail though, it just controls how the migration runs so that it doesn't exceed it.
